### ISSUE TITLE
Question: Media path build

### ISSUE THREAD

**Issue by marc0janssen** [vche/pycliarr#25]
Hi Vivien,

Why is a Series Path build without a (year), /media/Friends
And Why is a movie Path build with a (year),  /media/Fargo (2016)

I would like a Serie path also with a (year) added.

Is this possible?

Thanks Marco

**Comment by vche** [comment]
I don't build a year in series root path because each season has a different year. So it could be built based on the first season year, or the latest. it's a user's choice. I'll think about whether it makes sense to use the first season's year by default.

In the meantime you can build your own path as explained here: https://github.com/vche/pycliarr/issues/15 for an example of how to build your own path.

**Comment by marc0janssen** [comment]
Hi Vivien.

I always build my own path. That's not the issue. I would prefer the first year. That makes more sense.

Hope you can enable this.

Cheers. Marco

**Comment by vche** [comment]
If you build your own path then you can use the year you want. no update is needed on pycliarr ?

**Comment by marc0janssen** [comment]
Yes Vivien. I do it that way. No worry.

**Comment by vche** [comment]
I'm not sure I understand your initial request. Are you building your own path using the existing build_path() method in sonarr cli ? so having  a year by default in there would prevent you to write your own method ? If that's the case then as I said I might do this.

And in the meantime you can do something like this to unblock you immediately:
```
def build_serie_path(sonarr_cli, serie_info: SonarrSerieItem, root_folder_id: int = 0) -> Path:
        return sonarr_cli.build_item_path(serie_info.title + (f" ({serie_info.year})" if serie_info.year else ""))
```

**Comment by marc0janssen** [comment]
I build my own path, but thought it should be in pycliarr.
But like you said: You don’t know what some wants … initial year of current year.
So I keep building my own Path.

Thanks.
